#!/bin/bash
# Put this file into the directory $OPENSHIFT_REPO_DIR/.openshift/action_hooks/
# Rename it as "start" and give to it the eXecution permission (chmod +x ./start)
# The application will work only if it binds to $OPENSHIFT_INTERNAL_IP:8080
# -Dorient.baasbox.path=$OPENSHIFT_REPO_DIR/../data/baasbox the path od the data file, you should not modify this since this path
# -Dorient.baasbox.admin_password=admin the admin user password, modify it before launching BaasBox so to modify the admin pass at db creation time
# -Dapplication.code=1234567890 you MUST modify this to any valid string. This will be your application code

nohup java -Dorient.baasbox.path=$OPENSHIFT_REPO_DIR/../data/baasbox -Dorient.baasbox.admin_password=admin -Dapplication.code=1234567890 -Dhttp.port=8080 -Dhttp.address=$OPENSHIFT_INTERNAL_IP $* -cp "$OPENSHIFT_REPO_DIR/bin/lib/*" play.core.server.NettyServer $OPENSHIFT_REPO_DIR/bin $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
